import { userImg, userBck, telegram, arrow, 
  stock1, stock2, stock3, stars,
  img2, img3, img4, img5, img6, img7, img8
} from '../assets';

export const commodity_data = [
    {
        id:1,
        icon: userBck,
        userImg: userImg,
        userName: 'Aman Zain',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/1',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
    {
        id:2,
        icon: userBck,
        userImg: img2,
        userName: 'Amit Raj',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/2',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
    {
        id:3,
        icon: userBck,
        userImg: img3,
        userName: 'Raj Kumar',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/3',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
    {
        id:4,
        icon: userBck,
        userImg: img4,
        userName: 'Eeshee',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/4',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
    {
        id:5,
        icon: userBck,
        userImg: img5,
        userName: 'Vinit Kumar',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/5',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
    {
        id:6,
        icon: userBck,
        userImg: img6,
        userName: 'Parvez',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/6',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
    {
        id:7,
        icon: userBck,
        userImg: img7,
        userName: 'Deepak',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/7',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
    {
        id:8,
        icon: userBck,
        userImg: img8,
        userName: 'Arun Kumar',
        commodity: 'Commodity',
        telegramIcon: telegram,
        link: 'www.google.com/8',
        joinBtn: 'Join Telegram',
        arrow: arrow,
    },
]

export const stock_data = [
    {
      id: "1",
      content:
        "Our platform offers easy-to-use tools and customised services to traders, authorised by SEBI registered Research Analysts, making it simple to execute trades and manage the portfolio.",
      title: "For Traders",
      img: stock1,
      height: '380px'
    },
    {
      id: "2",
      content:
        "Connect with traders actively seeking valuable information, ensuring your analysis reaches an interested audience that enhances your visibility and credibility.",
      title: "For RAs",
      img: stock2,
      height: '350px'
    },
    {
      id: "3",
      content:
        "A one stop solution platform that provides a transparent access to comprehensive analysis and a vibrant network of traders and experts and resources needed for informed decision-making and profitable trading journeys.",
      name: "Kenn Gallagher",
      title: "",
      img: stock3,
      height:'400px'
    },
];

export const expertise_data = [
  {
    id: "1",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "2",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "3",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "4",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "5",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "6",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
];